name: Flutter Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ios:
    name: Build iOS application
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter build ipa --release --no-codesign
    - id: flutter-action
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: |
        echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
        echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
        echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
        echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
        echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
      shell: bash

  android:
    name: Build android application
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    - id: flutter-action
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: |
        echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
        echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
        echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
        echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
        echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
      shell: bash
