name: Flutter Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  web:
    name: Build web application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: |
        flutter clean
        flutter pub get
    - run: flutter build web --release
    - id: flutter-action
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: |
        echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
        echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
        echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
        echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
        echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
      shell: bash
    - name: Setup Pages
        uses: actions/configure-pages@v3
    - uses: actions/upload-artifact@v3
      with:
        path: |
          /Users/runner/work/weatherapp/weatherapp/build/web
    - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
